# Generated by Django 2.2 on 2020-04-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20200426_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall_message',
            name='likes',
            field=models.ManyToManyField(related_name='liked_messages', to='login_app.User'),
        ),
    ]
