# Generated by Django 2.2 on 2020-04-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_wall_message_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall_message',
            name='likes',
            field=models.ManyToManyField(related_name='liked_post', to='login_app.User'),
        ),
    ]
