# Generated by Django 2.2 on 2020-04-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_auto_20200426_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall_message',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='login_app.User'),
        ),
    ]
